/**
 * HEIC decoding (docs/decisions.md ADR-5): probe native support once (Safari
 * decodes HEIC via the system codec), otherwise lazy-load the libheif WASM
 * bundle as a separate chunk — it is downloaded only on the first HEIC task.
 */

import type { DecodedBmp as DecodedRgba } from './bmp';

/** 8×8 HEIC (496 bytes, generated by macOS sips) used for the native probe. */
const PROBE_HEIC_B64 =
  'AAAAJGZ0eXBoZWljAAAAAG1pZjFNaVBybWlhZk1pSEJoZWljAAABhm1ldGEAAAAAAAAAIWhkbHIAAAAAAAAAAHBpY3QAAAAAAAAAAAAAAAAAAAAAJGRpbmYAAAAcZHJlZgAAAAAAAAABAAAADHVybCAAAAABAAAADnBpdG0AAAAAAAEAAAAjaWluZgAAAAAAAQAAABVpbmZlAgAAAAABAABodmMxAAAAAOZpcHJwAAAAxWlwY28AAAATY29scm5jbHgAAgACAAaAAAAADGNsbGkAywBAAAAAFGlzcGUAAAAAAAAACAAAAAgAAAAJaXJvdAAAAAAQcGl4aQAAAAADCAgIAAAAcWh2Y0MBA3AAAACwAAAAAAAe8AD8/fj4AAALA6AAAQAXQAEMAf//A3AAAAMAsAAAAwAAAwAecCShAAEAI0IBAQNwAAADALAAAAMAAAMAHqAUIEHAmw7iHuRZVNwICBgCogABAAlEAcBnLIQFMkAAAAAZaXBtYQAAAAAAAAABAAEGgQIDBYaEAAAAHmlsb2MAAAAARAAAAQABAAAAAQAAAboAAAA2AAAAAW1kYXQAAAAAAAAARgAAADIoAa+i5vcKHwtsz/6UHC4cspv/Puy6nWfsVyzChudAbzKP98dh6CfQNtHrRVLssoXPgA==';

let nativeSupport: Promise<boolean> | null = null;

export function canDecodeHeicNatively(): Promise<boolean> {
  nativeSupport ??= (async () => {
    try {
      const bytes = Uint8Array.from(atob(PROBE_HEIC_B64), (c) => c.charCodeAt(0));
      const bitmap = await createImageBitmap(new Blob([bytes], { type: 'image/heic' }));
      bitmap.close();
      return true;
    } catch {
      return false;
    }
  })();
  return nativeSupport;
}

interface HeifImage {
  get_width(): number;
  get_height(): number;
  display(target: { data: Uint8ClampedArray; width: number; height: number },
          done: (result: unknown) => void): void;
  free?(): void;
}

interface Libheif {
  HeifDecoder: new () => { decode(data: Uint8Array): HeifImage[] };
}

let libheifPromise: Promise<Libheif> | null = null;

function loadLibheif(): Promise<Libheif> {
  // Self-contained ESM bundle (WASM embedded) → one lazy chunk, no asset
  // wiring. The default export is an emscripten module factory; the result
  // may be sync or a promise depending on the build, so always await it.
  libheifPromise ??= import('libheif-js/libheif-wasm/libheif-bundle.mjs').then(async (m) => {
    const factory = m.default as (opts?: object) => Libheif | Promise<Libheif>;
    return await factory();
  });
  return libheifPromise;
}

export async function decodeHeic(buffer: ArrayBuffer): Promise<DecodedRgba> {
  const libheif = await loadLibheif();
  const decoder = new libheif.HeifDecoder();
  const images = decoder.decode(new Uint8Array(buffer));
  if (!images || images.length === 0) throw new Error('HEIC: no decodable image found');
  try {
    const image = images[0];
    const width = image.get_width();
    const height = image.get_height();
    const data = new Uint8ClampedArray(width * height * 4);
    await new Promise<void>((resolve, reject) => {
      image.display({ data, width, height }, (result) =>
        result ? resolve() : reject(new Error('HEIC: libheif processing error')),
      );
    });
    return { width, height, data };
  } finally {
    for (const img of images) img.free?.();
  }
}
