/** Compatibility probe page (M0): verifies every browser API assumption the
 * architecture relies on. Results go into docs/decisions.md. */

type ProbeResult = { name: string; ok: boolean; note?: string };

document.getElementById('ua')!.textContent = navigator.userAgent;

function tinyPngBlob(): Blob {
  // 2×2 red PNG (generated by PIL).
  const b64 =
    'iVBORw0KGgoAAAANSUhEUgAAAAIAAAACCAIAAAD91JpzAAAAEklEQVR4nGM8IafBwMDAxAAGAA1yARJBWiM1AAAAAElFTkSuQmCC';
  return new Blob([Uint8Array.from(atob(b64), (c) => c.charCodeAt(0))], { type: 'image/png' });
}

function tinyBmpBlob(): Blob {
  // 2×2 24-bit bottom-up BMP, hand-built.
  const header = [
    0x42, 0x4d, 0x46, 0, 0, 0, 0, 0, 0, 0, 0x36, 0, 0, 0, 0x28, 0, 0, 0,
    2, 0, 0, 0, 2, 0, 0, 0, 1, 0, 24, 0, 0, 0, 0, 0, 0x10, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  ];
  const pixels = [255, 0, 0, 0, 255, 0, 0, 0, 0, 0, 0, 255, 0, 255, 0, 0];
  return new Blob([new Uint8Array([...header, ...pixels])], { type: 'image/bmp' });
}

async function probeHeicBlob(): Promise<Blob> {
  const res = await fetch('samples/probe.heic');
  return res.blob();
}

async function run(): Promise<void> {
  const results: ProbeResult[] = [];
  const add = (name: string, ok: boolean, note?: string) => results.push({ name, ok, note });

  add('Web Worker', typeof Worker !== 'undefined');
  add('OffscreenCanvas', typeof OffscreenCanvas !== 'undefined');

  try {
    const c = new OffscreenCanvas(4, 4);
    const ctx = c.getContext('2d');
    add('OffscreenCanvas 2d (главный поток)', !!ctx);
    const blob = await c.convertToBlob({ type: 'image/png' });
    add('convertToBlob', blob.size > 0, `${blob.size} байт`);
  } catch (e) {
    add('OffscreenCanvas 2d / convertToBlob', false, String(e));
  }

  for (const [name, blob] of [
    ['createImageBitmap(PNG)', tinyPngBlob()],
    ['createImageBitmap(BMP)', tinyBmpBlob()],
  ] as const) {
    try {
      const bmp = await createImageBitmap(blob);
      add(name, bmp.width > 0, `${bmp.width}×${bmp.height}`);
      bmp.close();
    } catch (e) {
      add(name, false, String(e));
    }
  }

  try {
    const bmp = await createImageBitmap(await probeHeicBlob());
    add('Нативное декодирование HEIC', bmp.width === 8, `${bmp.width}×${bmp.height}`);
    bmp.close();
  } catch (e) {
    add('Нативное декодирование HEIC', false, 'нет (будет использован libheif)');
    void e;
  }

  // Module worker + OffscreenCanvas 2d inside a worker, via an inline module.
  try {
    const src = `
      self.onmessage = async () => {
        try {
          const c = new OffscreenCanvas(4, 4);
          const ctx = c.getContext('2d');
          ctx.fillRect(0, 0, 4, 4);
          const blob = await c.convertToBlob({ type: 'image/png' });
          const bmp = await createImageBitmap(blob);
          bmp.close();
          self.postMessage({ ok: true });
        } catch (e) {
          self.postMessage({ ok: false, note: String(e) });
        }
      };`;
    const worker = new Worker(URL.createObjectURL(new Blob([src], { type: 'text/javascript' })), {
      type: 'module',
    });
    const result = await new Promise<{ ok: boolean; note?: string }>((resolve, reject) => {
      worker.onmessage = (e) => resolve(e.data);
      worker.onerror = (e) => reject(new Error(e.message));
      worker.postMessage(0);
      setTimeout(() => reject(new Error('таймаут')), 5000);
    });
    worker.terminate();
    add('Module worker + canvas-конвейер в worker', result.ok, result.note);
  } catch (e) {
    add('Module worker + canvas-конвейер в worker', false, String(e));
  }

  // 15 Mpx canvas (5000×3000).
  try {
    const c = new OffscreenCanvas(5000, 3000);
    const ctx = c.getContext('2d', { willReadFrequently: true })!;
    ctx.fillStyle = '#234';
    ctx.fillRect(0, 0, 5000, 3000);
    const d = ctx.getImageData(4999, 2999, 1, 1);
    add('Canvas 15 Мпк (5000×3000)', d.data[3] === 255);
  } catch (e) {
    add('Canvas 15 Мпк (5000×3000)', false, String(e));
  }

  const rows = results
    .map(
      (r) =>
        `<tr><td>${r.name}</td><td>${r.ok ? '✓' : '✗'}</td><td>${r.note ?? ''}</td></tr>`,
    )
    .join('');
  document.getElementById('results')!.innerHTML =
    `<table><tr><th>Проверка</th><th>Результат</th><th>Примечание</th></tr>${rows}</table>`;
}

void run();
